// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/workflows": {
    params: {};
  };
  "/workflows/:id": {
    params: {
      "id": string;
    };
  };
  "/access-denied": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/callback/:provider" | "/workflows" | "/workflows/:id" | "/access-denied";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/callback.$provider.tsx": {
    id: "routes/callback.$provider";
    page: "/callback/:provider";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/workflows._index.tsx": {
    id: "routes/workflows._index";
    page: "/workflows";
  };
  "routes/workflows.$id.tsx": {
    id: "routes/workflows.$id";
    page: "/workflows/:id";
  };
  "routes/access-denied.tsx": {
    id: "routes/access-denied";
    page: "/access-denied";
  };
};